name: Unity Test

# Run test when push or pull request is made
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:

    # Check out to access code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Unity
    - name: Setup Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2021.3.42f1
        targetPlatform: StandaloneWindows64

    # Run tests under ../Test/EditMode/.. or ../Test/PlayMode..
    - name: Run unit tests
      uses: game-ci/unity-test-runner@v2
      with:
        unityVersion: 2021.3.42f1
        targetPlatform: StandaloneWindows64
