name: Unity Test Demo

# Run test when push or pull request is made
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:

    - run: echo "Test triggered by ${{github.event_name}} event."
    
    # Check out to access code
    - name: Checkout repository
      uses: actions/checkout@v3
    - run: echo "1/3 ... Repo ${{github.repository}} has been cloned to runner."

    # Install Unity
    - name: Setup Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2021.3.42f1
        targetPlatform: StandaloneWindows64
    - run: echo "2/3 ... Workflow ready for test."

    # Run tests under ../Test/EditMode/.. or ../Test/PlayMode..
    - name: Run unit tests
      uses: game-ci/unity-test-runner@v2
      with:
        unityVersion: 2021.3.42f1
        targetPlatform: StandaloneWindows64
    - run: echo "3/3 ... Passed all tests successfully."
